# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 101, 16))
        self.label_2.setObjectName("label_2")
        self.StartAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.StartAddress.setGeometry(QtCore.QRect(190, 110, 104, 31))
        self.StartAddress.setObjectName("StartAddress")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 170, 101, 16))
        self.label_3.setObjectName("label_3")
        self.FilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.FilePath.setGeometry(QtCore.QRect(190, 60, 104, 31))
        self.FilePath.setObjectName("FileName")
        self.EndAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.EndAddress.setGeometry(QtCore.QRect(190, 160, 104, 31))
        self.EndAddress.setObjectName("EndAddress")
        self.TraceText = QtWidgets.QLineEdit(self.centralwidget)
        self.TraceText.setGeometry(QtCore.QRect(190, 310, 104, 31))
        self.TraceText.setObjectName("TraceText")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 310, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 220, 101, 16))
        self.label_4.setObjectName("label_4")
        self.CPU_MODEL = QtWidgets.QLineEdit(self.centralwidget)
        self.CPU_MODEL.setGeometry(QtCore.QRect(190, 210, 104, 31))
        self.CPU_MODEL.setObjectName("CPU_MODEL")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 270, 101, 16))
        self.label_5.setObjectName("label_5")
        self.Model = QtWidgets.QLineEdit(self.centralwidget)
        self.Model.setGeometry(QtCore.QRect(190, 260, 104, 31))
        self.Model.setObjectName("Model")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 380, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deobf"))
        self.label.setText(_translate("MainWindow", "文件名"))
        self.label_2.setText(_translate("MainWindow", "混淆函数开始地址"))
        self.label_3.setText(_translate("MainWindow", "混淆函数结束地址"))
        self.label_4.setText(_translate("MainWindow", "目前cpu模式"))
        self.label_5.setText(_translate("MainWindow", "真实块识别算法"))
        self.label_6.setText(_translate("MainWindow", "trace目录"))
        self.pushButton.setText(_translate("MainWindow", "去混淆"))
